apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    name: monogmetadata
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodbpodlebel
  template:
    metadata:
      labels:
        name: mongodbpodlebel
    spec:
      containers:
        - image: mongo
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data/db
              name: myvol
          name: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: 'dummy'
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: 'dummy'
      volumes:
        - name: myvol
          persistentVolumeClaim:
            claimName: myclaim