apiVersion: apps/v1
kind: Deployment
metadata:
  name: monogmetadata
  labels:
    name: ku
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodbpodlebel
  template:
    metadata:
      labels:
        name: mongodbpodlebel
    spec:
      containers:
      - name: mongodbcontainer
        image: mongo
        ports:
        - containerPort: 27017
        envFrom:
        - secretRef:
          name: mysecret
        
        
        
        
